// Login User
POST http://localhost:5050/auth/login
Content-Type: application/json

{
  "email": "suadmin@urbanathletes.co.id",
  "password": "Urban1234"
}

###
// get Auth
GET http://localhost:5050/auth/me
Content-Type: application/json 
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiZGE1YjljY2QtMDhhNC00MjAwLWE1ZjktYjI2OGYxYzhmYmE1IiwibmFtZSI6IlN1cGVyIEFkbWluIiwiZW1haWwiOiJzdWFkbWluQHVyYmFuYXRobGV0ZXMuY28uaWQiLCJyb2xlSWQiOjEsInJvbGUiOiJTdXBlciBBZG1pbiIsImlhdCI6MTY2NDc5Mzc2OCwiZXhwIjoxNjY0ODgwMTY4fQ.MAD3flxuVQ011VoBZtQRLxeDmHJPqmRVYCZjaVuva2k


###
// Logout User
DELETE http://localhost:5050/auth/logout
Content-Type: application/json