// Login User
POST http://localhost:5050/auth/login
Content-Type: application/json

{
  "email": "suadmin@urbanathletes.co.id",
  "password": "Urban1234"
}

###
// get Auth
GET http://localhost:5050/auth/me
Content-Type: application/json

###
// Logout User
DELETE http://localhost:5050/auth/logout
Content-Type: application/json