// get All user
GET http://localhost:5050/users
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiZGE1YjljY2QtMDhhNC00MjAwLWE1ZjktYjI2OGYxYzhmYmE1IiwibmFtZSI6IlN1cGVyIEFkbWluIiwiZW1haWwiOiJzdWFkbWluQHVyYmFuYXRobGV0ZXMuY28uaWQiLCJyb2xlSWQiOjEsImlhdCI6MTY2NDM4MzcxOSwiZXhwIjoxNjY0NDcwMTE5fQ.dGO9eV-T9-gwHaP7Vhf-sBC6CKjFrJHsoTWlZCYjhAw

###
//get User By Id
GET http://localhost:5050/users/2feffe17-45af-4f48-b13b-564c57cb5421
Content-Type: application/json

###
//Create User
POST http://localhost:5050/users
Content-Type: application/json

{
  "name": "Manager",
  "email": "manager@urbanathletes.co.id",
  "password": "Urban1234",
  "confPassword": "Urban1234",
  "roleId": 3
}

###
//Update User
PUT http://localhost:5050/users/d0bc2061-6930-46b8-8c4d-bc3a1e2fe66d
Content-Type: application/json

{
  "name": "Managercoba update",
  "email": "manager1@urbanathletes.co.id",
  "password": "",
  "confPassword": "",
  "roleId": 2
}

###
// Delete User
DELETE http://localhost:5050/users
Content-Type: application/json

{
  "id": "d0bc2061-6930-46b8-8c4d-bc3a1e2fe66d"
}