// get All user
GET http://localhost:5050/users
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiMmUzYjI3MzgtYjlhNy00MzU3LTkxOGUtOGFhN2VmNmI0YTQ3IiwibmFtZSI6IlN1cGVyIEFkbWluIiwiZW1haWwiOiJzdWFkbWluQHVyYmFuYXRobGV0ZXMuY28uaWQiLCJyb2xlSWQiOjEsInJvbGUiOiJTdXBlciBhZG1pbiIsImlhdCI6MTY2NjA2NDM4MywiZXhwIjoxNjY2MTUwNzgzfQ.yBkQXyHqOqweK6eZBwqMt4OJsJS-lO3IJbcY3dYTUsg

###
//get User By Id
GET http://localhost:5050/users/2feffe17-45af-4f48-b13b-564c57cb5421
Content-Type: application/json

###
//Create User
POST http://localhost:5050/users
Content-Type: application/json

{
  "name": "Super Admin",
  "email": "suadmin@urbanathletes.co.id",
  "password": "Urban1234",
  "confPassword": "Urban1234",
  "roleId": 1
}

###
//Update User
PUT http://localhost:5050/users/d0bc2061-6930-46b8-8c4d-bc3a1e2fe66d
Content-Type: application/json

{
  "name": "Managercoba update",
  "email": "manager1@urbanathletes.co.id",
  "password": "",
  "confPassword": "",
  "roleId": 2
}

###
// Delete User
DELETE http://localhost:5050/users
Content-Type: application/json

{
  "id": "d0bc2061-6930-46b8-8c4d-bc3a1e2fe66d"
}